import type { Exercise, ExerciseId, MuscleGroup } from '@domain/catalog';
import type { Incoming } from '@domain/timestamps';

/**
 * Read-only access to the muscle group catalog.
 *
 * The catalog ships with the app — there is no create/update/delete operation.
 * See 02 · Domain Model ("Группа мышц — фиксированный enum прямо на упражнении")
 * and 07 · Persistence Layer Contract ("MuscleGroupRepository").
 *
 * All methods are asynchronous per hard rule 1, even though the current
 * (local SQLite) adapter has no real I/O to await.
 */
export interface MuscleGroupRepository {
  /** All muscle groups in the catalog. */
  getAll(): Promise<MuscleGroup[]>;

  /** A single muscle group, or `null` if it is not part of the catalog. */
  getById(id: MuscleGroup): Promise<MuscleGroup | null>;
}

/**
 * Access to the exercise catalog and to the user's custom exercises.
 *
 * `Exercise` is a single table with two origins (`source: 'catalog' | 'custom'`,
 * see 02 · Domain Model). Records with `source = 'catalog'` are immutable and can
 * only ever be hidden — they are never edited or deleted through this repository.
 * `createCustom` / `updateCustom` operate on `source = 'custom'` records only.
 *
 * Ids are generated by the domain before the entity is passed in here (hard rule 3):
 * this repository never generates an id itself.
 *
 * See 07 · Persistence Layer Contract, "Hard rules" and "ExerciseRepository".
 */
export interface ExerciseRepository {
  /** All exercises, catalog and custom, including hidden ones. */
  getAll(): Promise<Exercise[]>;

  /** A single exercise by id, or `null` if it does not exist. */
  getById(id: ExerciseId): Promise<Exercise | null>;

  /**
   * Exercises matching the given ids, in no particular order. Ids that don't
   * resolve to an exercise are silently omitted from the result.
   */
  listByIds(ids: readonly ExerciseId[]): Promise<Exercise[]>;

  /** All exercises belonging to the given muscle group. */
  filterByMuscleGroup(muscleGroup: MuscleGroup): Promise<Exercise[]>;

  /**
   * Persists a new custom exercise. The caller supplies a fully-formed
   * `Exercise` (id already generated, `source: 'custom'`) — this method only
   * writes it, it does not construct or validate the entity.
   */
  createCustom(exercise: Incoming<Exercise>): Promise<Exercise>;

  /**
   * Replaces an existing custom exercise with the given entity (matched by
   * `id`). Rejects if the record does not exist or is not `source: 'custom'`.
   */
  updateCustom(exercise: Exercise): Promise<Exercise>;

  /**
   * Flips `isHidden` on the exercise with the given id (catalog or custom)
   * and returns the updated entity. Rejects if the record does not exist.
   */
  toggleHidden(id: ExerciseId): Promise<Exercise>;

  /**
   * Seeds the catalog with the given `source: 'catalog'` exercises. Matches by the exercises'
   * (pre-baked) ids: existing records — catalog or custom — are left untouched, only missing
   * catalog ids are inserted.
   *
   * The app itself no longer calls this: since 067(2) the catalog reaches a SQLite database as
   * migration `drizzle/0001_seed_catalog.sql`, so the migration journal decides what has been
   * seeded. It stays on the interface because it is how a store is filled with catalog exercises
   * — which is what every test that needs some does, on either adapter.
   */
  seedCatalog(exercises: readonly Incoming<Exercise>[]): Promise<void>;
}
