import type { Mesocycle } from '@domain/mesocycle';
import type { Incoming } from '@domain/timestamps';

/**
 * Access to mesocycles (training blocks).
 *
 * Ids are generated by the domain before create() is called (hard rule 3):
 * this repository never generates an id itself. See 07 · Persistence Layer
 * Contract, "Hard rules" and "MesocycleRepository".
 *
 * All methods are asynchronous per hard rule 1, even though the current
 * (in-memory/local) adapter has no real I/O to await. No business logic
 * lives here (hard rule 2) — reading, writing, and simple filtering only.
 */
export interface MesocycleRepository {
  /** All mesocycles. */
  getAll(): Promise<Mesocycle[]>;

  /** A single mesocycle by id, or `null` if it does not exist. */
  getById(id: string): Promise<Mesocycle | null>;

  /**
   * The one mesocycle with `status: 'active'`, or `null` if none is active.
   * At most one mesocycle is active at a time (02 · Domain Model).
   */
  getActive(): Promise<Mesocycle | null>;

  /** Persists a new mesocycle that already carries its domain-generated id. */
  create(mesocycle: Incoming<Mesocycle>): Promise<Mesocycle>;

  /** Persists changes to an existing mesocycle, addressed by its id. */
  update(mesocycle: Mesocycle): Promise<Mesocycle>;

  /**
   * Removes a mesocycle by id along with all of its child data (sessions,
   * session exercises, set logs, etc.) — see 07 · Persistence Layer Contract,
   * "Удалить со всеми дочерними данными".
   */
  deleteWithChildren(id: string): Promise<void>;
}
