import type { Session } from '@domain/execution';

/**
 * Access to `Session` — one workout within a mesocycle, materialized lazily
 * (07 · Persistence Layer Contract). Session generation, the progression engine, and
 * next-session creation all read and write through this contract.
 *
 * Ids are generated by the domain before the entity is passed in here (hard rule 3):
 * this repository never generates an id itself.
 *
 * See 02 · Domain Model, "Session", and 07 · Persistence Layer Contract, "Hard rules"
 * and "SessionRepository".
 */
export interface SessionRepository {
  /** A single session by id, or `null` if it does not exist. */
  getById(id: string): Promise<Session | null>;

  /** Every session belonging to the given mesocycle. */
  listByMesoId(mesoId: string): Promise<Session[]>;

  /** Every session belonging to the given mesocycle and week number. */
  listByMesoIdAndWeekNumber(mesoId: string, weekNumber: number): Promise<Session[]>;

  /**
   * The most recently completed session for the given mesocycle and day number, or
   * `null` if none of that day has been completed yet. This is the source session the
   * progression engine reads from when generating the next week's plan for that day
   * (03 · Progression Engine, "Ленивая генерация по дням") — the adapter must keep an
   * index on `(mesoId, dayNumber)` rather than scanning every session
   * (07, "Критичные по производительности запросы").
   */
  getLastCompletedByMesoIdAndDayNumber(mesoId: string, dayNumber: number): Promise<Session | null>;

  /**
   * The session currently `in_progress`, or `null` if none is. Only one session across
   * the whole app can be `in_progress` at a time (02 · Domain Model, "Session", invariants).
   */
  getCurrentInProgress(): Promise<Session | null>;

  /** Persists a session that already carries its domain-generated id. */
  create(session: Session): Promise<Session>;

  /** Persists several sessions in one call — used when materializing a week's worth of days. */
  createMany(sessions: readonly Session[]): Promise<Session[]>;

  /** Persists changes to an existing session, addressed by its id. */
  update(session: Session): Promise<Session>;
}
