import type { SessionExercise } from '@domain/execution';

/**
 * Access to `SessionExercise` — the plan for one exercise within a session, a
 * materialized `WeekPlanExercise` plus its calculated targets (02 · Domain Model,
 * "SessionExercise").
 *
 * Ids are generated by the domain before the entity is passed in here (hard rule 3):
 * this repository never generates an id itself.
 *
 * See 07 · Persistence Layer Contract, "Hard rules" and "SessionExerciseRepository".
 */
export interface SessionExerciseRepository {
  /** Every exercise planned within the given session, in no particular order. */
  listBySessionId(sessionId: string): Promise<SessionExercise[]>;

  /** Persists a session exercise that already carries its domain-generated id. */
  create(sessionExercise: SessionExercise): Promise<SessionExercise>;

  /** Persists several session exercises in one call — used when materializing a session. */
  createMany(sessionExercises: readonly SessionExercise[]): Promise<SessionExercise[]>;

  /** Persists changes to an existing session exercise, addressed by its id. */
  update(sessionExercise: SessionExercise): Promise<SessionExercise>;

  /**
   * Persists changes to several existing session exercises in one call — used for
   * bulk changes made during a workout (e.g. reordering every exercise in a session).
   */
  updateMany(sessionExercises: readonly SessionExercise[]): Promise<SessionExercise[]>;

  /** Removes a session exercise by id. */
  deleteById(id: string): Promise<void>;
}
