import type { MesoTemplate } from '@domain/plan';
import type { Incoming } from '@domain/timestamps';

/**
 * Access to the mesocycle template catalog and to the user's custom
 * templates.
 *
 * `MesoTemplate` is a single table with two origins (`source: 'catalog' |
 * 'custom'`, see 02 · Domain Model), the same split as `Exercise`. Records
 * with `source = 'catalog'` are immutable and can only ever be hidden.
 * `source = 'custom'` records are saved by the user from their own
 * mesocycles and are freely editable.
 *
 * Ids are generated by the domain before the entity is passed in here (hard
 * rule 3): this repository never generates an id itself. It also carries no
 * business logic (hard rule 2) — it only stores and retrieves whatever
 * `MesoTemplate` it is given.
 *
 * See 07 · Persistence Layer Contract, "Hard rules" and "TemplateRepository".
 *
 * All methods are asynchronous per hard rule 1, even though the current
 * (local SQLite) adapter has no real I/O to await.
 */
export interface TemplateRepository {
  /** All templates, catalog and custom, including hidden ones. */
  getAll(): Promise<MesoTemplate[]>;

  /** A single template by id, or `null` if it does not exist. */
  getById(id: string): Promise<MesoTemplate | null>;

  /**
   * Persists a new template. The caller supplies a fully-formed
   * `MesoTemplate` (id already generated) — this method only writes it, it
   * does not construct or validate the entity.
   */
  create(template: Incoming<MesoTemplate>): Promise<MesoTemplate>;

  /**
   * Replaces an existing template with the given entity (matched by `id`).
   * Rejects if the record does not exist.
   */
  update(template: MesoTemplate): Promise<MesoTemplate>;

  /** Deletes the template with the given id. Rejects if it does not exist. */
  deleteById(id: string): Promise<void>;
}
