import migrations from '../../drizzle/migrations';

import type { MigrationBundle } from './migrations';

/**
 * The app's migrations as the bundler carries them (task 069).
 *
 * `drizzle/migrations.js` is generated by `drizzle-kit generate` next to the SQL itself, and
 * exists because Metro has no filesystem to read migrations from at runtime: it imports the
 * journal and every `.sql` file statically, so they end up in the bundle as ordinary modules.
 * This file is the one place that import lives, so nothing else has to know that shape.
 *
 * Tests read the same migrations off disk instead (`__tests__/fixtures/sqliteDatabase.ts`) —
 * Node can, and it saves teaching Jest to transform `.sql`. Same files either way.
 */
export const MIGRATION_BUNDLE: MigrationBundle = migrations;
