// Stub catalog exercises — see 02 · Domain Model ("Exercise") and Tasks/028
// ("Stub-данные: каталог упражнений"). A plain TS array, not JSON: ids are
// hand-picked slugs baked into the app (same reasoning as MUSCLE_GROUPS in
// ./catalog.ts — "Идентификаторы каталога прошиты в приложение"), and every
// field is checked against the domain's own MuscleGroup/Equipment unions at
// compile time. Feed this into ExerciseRepository.seedCatalog(catalogVersion,
// EXERCISE_CATALOG) to populate a store; this file has no side effects of its
// own and does not call the repository.
import type { Exercise } from './catalog';
import { toExerciseId } from './catalog';
import type { Unsaved } from './timestamps';

export const EXERCISE_CATALOG: readonly Unsaved<Exercise>[] = [
  // Chest
  {
    id: toExerciseId('bench-press-barbell'),
    name: 'Bench Press',
    muscleGroup: 'chest',
    source: 'catalog',
    equipment: 'barbell',
    isHidden: false,
  },
  {
    id: toExerciseId('incline-bench-press-barbell'),
    name: 'Incline Bench Press',
    muscleGroup: 'chest',
    source: 'catalog',
    equipment: 'barbell',
    isHidden: false,
  },
  {
    id: toExerciseId('bench-press-dumbbell'),
    name: 'Bench Press',
    muscleGroup: 'chest',
    source: 'catalog',
    equipment: 'dumbbell',
    isHidden: false,
  },
  {
    id: toExerciseId('incline-bench-press-dumbbell'),
    name: 'Incline Bench Press',
    muscleGroup: 'chest',
    source: 'catalog',
    equipment: 'dumbbell',
    isHidden: false,
  },
  {
    id: toExerciseId('chest-press-machine'),
    name: 'Chest Press',
    muscleGroup: 'chest',
    source: 'catalog',
    equipment: 'machine',
    isHidden: false,
  },
  {
    id: toExerciseId('cable-fly-cable'),
    name: 'Cable Fly',
    muscleGroup: 'chest',
    source: 'catalog',
    equipment: 'cable',
    isHidden: false,
  },
  {
    id: toExerciseId('pec-deck-machine'),
    name: 'Pec Deck',
    muscleGroup: 'chest',
    source: 'catalog',
    equipment: 'machine',
    isHidden: false,
  },
  {
    id: toExerciseId('push-up-bodyweight'),
    name: 'Push Up',
    muscleGroup: 'chest',
    source: 'catalog',
    equipment: 'bodyweight',
    isHidden: false,
  },
  {
    id: toExerciseId('dips-chest-focused-bodyweight'),
    name: 'Dips Chest Focused',
    muscleGroup: 'chest',
    source: 'catalog',
    equipment: 'bodyweight',
    isHidden: false,
  },
  {
    id: toExerciseId('dips-chest-focused-weighted-bodyweight'),
    name: 'Dips Chest Focused Weighted',
    muscleGroup: 'chest',
    source: 'catalog',
    equipment: 'bodyweight-weighted',
    isHidden: false,
  },

  // Shoulders
  {
    id: toExerciseId('shoulder-press-barbell'),
    name: 'Shoulder Press',
    muscleGroup: 'shoulders',
    source: 'catalog',
    equipment: 'barbell',
    isHidden: false,
  },
  {
    id: toExerciseId('shoulder-press-dumbbell'),
    name: 'Shoulder Press',
    muscleGroup: 'shoulders',
    source: 'catalog',
    equipment: 'dumbbell',
    isHidden: false,
  },
  {
    id: toExerciseId('shoulder-press-machine'),
    name: 'Shoulder Press',
    muscleGroup: 'shoulders',
    source: 'catalog',
    equipment: 'machine',
    isHidden: false,
  },
  {
    id: toExerciseId('lateral-raise-dumbbell'),
    name: 'Lateral Raise',
    muscleGroup: 'shoulders',
    source: 'catalog',
    equipment: 'dumbbell',
    isHidden: false,
  },
  {
    id: toExerciseId('lateral-raise-cable'),
    name: 'Lateral Raise',
    muscleGroup: 'shoulders',
    source: 'catalog',
    equipment: 'cable',
    isHidden: false,
  },
  {
    id: toExerciseId('rear-delt-fly-dumbbell'),
    name: 'Rear Delt Fly',
    muscleGroup: 'shoulders',
    source: 'catalog',
    equipment: 'dumbbell',
    isHidden: false,
  },
  {
    id: toExerciseId('rear-delt-fly-cable'),
    name: 'Rear Delt Fly',
    muscleGroup: 'shoulders',
    source: 'catalog',
    equipment: 'cable',
    isHidden: false,
  },
  {
    id: toExerciseId('face-pull-cable'),
    name: 'Face Pull',
    muscleGroup: 'shoulders',
    source: 'catalog',
    equipment: 'cable',
    isHidden: false,
  },
  {
    id: toExerciseId('front-raise-dumbbell'),
    name: 'Front Raise',
    muscleGroup: 'shoulders',
    source: 'catalog',
    equipment: 'dumbbell',
    isHidden: false,
  },

  // Triceps
  {
    id: toExerciseId('triceps-pushdown-cable'),
    name: 'Triceps Pushdown',
    muscleGroup: 'triceps',
    source: 'catalog',
    equipment: 'cable',
    isHidden: false,
  },
  {
    id: toExerciseId('triceps-extension-cable'),
    name: 'Triceps Extension',
    muscleGroup: 'triceps',
    source: 'catalog',
    equipment: 'cable',
    isHidden: false,
  },
  {
    id: toExerciseId('triceps-extension-overhead-cable'),
    name: 'Triceps Extension Overhead',
    muscleGroup: 'triceps',
    source: 'catalog',
    equipment: 'cable',
    isHidden: false,
  },
  {
    id: toExerciseId('close-grip-bench-press-barbell'),
    name: 'Close-Grip Bench Press',
    muscleGroup: 'triceps',
    source: 'catalog',
    equipment: 'barbell',
    isHidden: false,
  },
  {
    id: toExerciseId('skull-crusher-dumbbell'),
    name: 'Skull Crusher',
    muscleGroup: 'triceps',
    source: 'catalog',
    equipment: 'dumbbell',
    isHidden: false,
  },
  {
    id: toExerciseId('skull-crusher-machine'),
    name: 'Skull Crusher',
    muscleGroup: 'triceps',
    source: 'catalog',
    equipment: 'machine',
    isHidden: false,
  },
  {
    id: toExerciseId('triceps-extension-dumbbell'),
    name: 'Triceps Extension',
    muscleGroup: 'triceps',
    source: 'catalog',
    equipment: 'dumbbell',
    isHidden: false,
  },
  {
    id: toExerciseId('dip-bodyweight'),
    name: 'Dip',
    muscleGroup: 'triceps',
    source: 'catalog',
    equipment: 'bodyweight',
    isHidden: false,
  },
  {
    id: toExerciseId('triceps-extension-machine'),
    name: 'Triceps Extension',
    muscleGroup: 'triceps',
    source: 'catalog',
    equipment: 'machine',
    isHidden: false,
  },

  // Back
  {
    id: toExerciseId('pull-up-bodyweight'),
    name: 'Pull Up',
    muscleGroup: 'back',
    source: 'catalog',
    equipment: 'bodyweight',
    isHidden: false,
  },
  {
    id: toExerciseId('pull-up-weighted-bodyweight'),
    name: 'Pull Up Weighted',
    muscleGroup: 'back',
    source: 'catalog',
    equipment: 'bodyweight-weighted',
    isHidden: false,
  },
  {
    id: toExerciseId('lat-pulldown-cable'),
    name: 'Lat Pulldown',
    muscleGroup: 'back',
    source: 'catalog',
    equipment: 'cable',
    isHidden: false,
  },
  {
    id: toExerciseId('lat-pulldown-parallel-grip-cable'),
    name: 'Lat Pulldown Parallel Grip',
    muscleGroup: 'back',
    source: 'catalog',
    equipment: 'cable',
    isHidden: false,
  },
  {
    id: toExerciseId('seated-row-cable'),
    name: 'Seated Row',
    muscleGroup: 'back',
    source: 'catalog',
    equipment: 'cable',
    isHidden: false,
  },
  {
    id: toExerciseId('barbell-row-barbell'),
    name: 'Barbell Row',
    muscleGroup: 'back',
    source: 'catalog',
    equipment: 'barbell',
    isHidden: false,
  },
  {
    id: toExerciseId('dumbbell-row-dumbbell'),
    name: 'Dumbbell Row',
    muscleGroup: 'back',
    source: 'catalog',
    equipment: 'dumbbell',
    isHidden: false,
  },
  {
    id: toExerciseId('t-bar-row-other'),
    name: 'T-Bar Row',
    muscleGroup: 'back',
    source: 'catalog',
    equipment: 'other',
    isHidden: false,
  },
  {
    id: toExerciseId('chest-supported-row-machine'),
    name: 'Chest-Supported Row',
    muscleGroup: 'back',
    source: 'catalog',
    equipment: 'machine',
    isHidden: false,
  },
  {
    id: toExerciseId('straight-arm-pulldown-cable'),
    name: 'Straight-Arm Pulldown',
    muscleGroup: 'back',
    source: 'catalog',
    equipment: 'cable',
    isHidden: false,
  },
  {
    id: toExerciseId('deadlift-barbell'),
    name: 'Deadlift',
    muscleGroup: 'back',
    source: 'catalog',
    equipment: 'barbell',
    isHidden: false,
  },

  // Biceps
  {
    id: toExerciseId('bicep-curl-barbell'),
    name: 'Bicep Curl',
    muscleGroup: 'biceps',
    source: 'catalog',
    equipment: 'barbell',
    isHidden: false,
  },
  {
    id: toExerciseId('bicep-curl-dumbbell'),
    name: 'Bicep Curl',
    muscleGroup: 'biceps',
    source: 'catalog',
    equipment: 'dumbbell',
    isHidden: false,
  },
  {
    id: toExerciseId('bicep-curl-alternating-dumbbell'),
    name: 'Bicep Curl Alternating',
    muscleGroup: 'biceps',
    source: 'catalog',
    equipment: 'dumbbell',
    isHidden: false,
  },
  {
    id: toExerciseId('bicep-curl-cable'),
    name: 'Bicep Curl',
    muscleGroup: 'biceps',
    source: 'catalog',
    equipment: 'cable',
    isHidden: false,
  },
  {
    id: toExerciseId('incline-curl-dumbbell'),
    name: 'Incline Curl',
    muscleGroup: 'biceps',
    source: 'catalog',
    equipment: 'dumbbell',
    isHidden: false,
  },
  {
    id: toExerciseId('hammer-curl-dumbbell'),
    name: 'Hammer Curl',
    muscleGroup: 'biceps',
    source: 'catalog',
    equipment: 'dumbbell',
    isHidden: false,
  },
  {
    id: toExerciseId('preacher-curl-machine'),
    name: 'Preacher Curl',
    muscleGroup: 'biceps',
    source: 'catalog',
    equipment: 'machine',
    isHidden: false,
  },
  {
    id: toExerciseId('concentration-curl-dumbbell'),
    name: 'Concentration Curl',
    muscleGroup: 'biceps',
    source: 'catalog',
    equipment: 'dumbbell',
    isHidden: false,
  },

  // Forearms
  {
    id: toExerciseId('wrist-curl-dumbbell'),
    name: 'Wrist Curl',
    muscleGroup: 'forearms',
    source: 'catalog',
    equipment: 'dumbbell',
    isHidden: false,
  },
  {
    id: toExerciseId('reverse-wrist-curl-dumbbell'),
    name: 'Reverse Wrist Curl',
    muscleGroup: 'forearms',
    source: 'catalog',
    equipment: 'dumbbell',
    isHidden: false,
  },
  {
    id: toExerciseId('reverse-curl-barbell'),
    name: 'Reverse Curl',
    muscleGroup: 'forearms',
    source: 'catalog',
    equipment: 'barbell',
    isHidden: false,
  },
  {
    id: toExerciseId('farmers-carry-dumbbell'),
    name: "Farmer's Carry",
    muscleGroup: 'forearms',
    source: 'catalog',
    equipment: 'dumbbell',
    isHidden: false,
  },

  // Quads
  {
    id: toExerciseId('squat-barbell'),
    name: 'Squat',
    muscleGroup: 'quads',
    source: 'catalog',
    equipment: 'barbell',
    isHidden: false,
  },
  {
    id: toExerciseId('leg-press-machine'),
    name: 'Leg Press',
    muscleGroup: 'quads',
    source: 'catalog',
    equipment: 'machine',
    isHidden: false,
  },
  {
    id: toExerciseId('leg-extension-machine'),
    name: 'Leg Extension',
    muscleGroup: 'quads',
    source: 'catalog',
    equipment: 'machine',
    isHidden: false,
  },
  {
    id: toExerciseId('hack-squat-machine'),
    name: 'Hack Squat',
    muscleGroup: 'quads',
    source: 'catalog',
    equipment: 'machine',
    isHidden: false,
  },
  {
    id: toExerciseId('front-squat-barbell'),
    name: 'Front Squat',
    muscleGroup: 'quads',
    source: 'catalog',
    equipment: 'barbell',
    isHidden: false,
  },
  {
    id: toExerciseId('front-squat-kettlebell-other'),
    name: 'Front Squat Kettlebell',
    muscleGroup: 'quads',
    source: 'catalog',
    equipment: 'other',
    isHidden: false,
  },
  {
    id: toExerciseId('bulgarian-split-squat-dumbbell'),
    name: 'Bulgarian Split Squat',
    muscleGroup: 'quads',
    source: 'catalog',
    equipment: 'dumbbell',
    isHidden: false,
  },
  {
    id: toExerciseId('lunge-dumbbell'),
    name: 'Lunge',
    muscleGroup: 'quads',
    source: 'catalog',
    equipment: 'dumbbell',
    isHidden: false,
  },
  {
    id: toExerciseId('goblet-squat-dumbbell'),
    name: 'Goblet Squat',
    muscleGroup: 'quads',
    source: 'catalog',
    equipment: 'dumbbell',
    isHidden: false,
  },
  {
    id: toExerciseId('sissy-squat-bodyweight'),
    name: 'Sissy Squat',
    muscleGroup: 'quads',
    source: 'catalog',
    equipment: 'bodyweight',
    isHidden: false,
  },
  {
    id: toExerciseId('sissy-squat-weighted-bodyweight'),
    name: 'Sissy Squat Weighted',
    muscleGroup: 'quads',
    source: 'catalog',
    equipment: 'bodyweight-weighted',
    isHidden: false,
  },

  // Hamstrings
  {
    id: toExerciseId('stiff-legged-deadlift-barbell'),
    name: 'Stiff-Legged Deadlift',
    muscleGroup: 'hamstrings',
    source: 'catalog',
    equipment: 'barbell',
    isHidden: false,
  },
  {
    id: toExerciseId('stiff-legged-deadlift-dumbbell'),
    name: 'Stiff-Legged Deadlift',
    muscleGroup: 'hamstrings',
    source: 'catalog',
    equipment: 'dumbbell',
    isHidden: false,
  },
  {
    id: toExerciseId('lying-leg-curl-machine'),
    name: 'Lying Leg Curl',
    muscleGroup: 'hamstrings',
    source: 'catalog',
    equipment: 'machine',
    isHidden: false,
  },
  {
    id: toExerciseId('seated-leg-curl-machine'),
    name: 'Seated Leg Curl',
    muscleGroup: 'hamstrings',
    source: 'catalog',
    equipment: 'machine',
    isHidden: false,
  },
  {
    id: toExerciseId('good-morning-barbell'),
    name: 'Good Morning',
    muscleGroup: 'hamstrings',
    source: 'catalog',
    equipment: 'barbell',
    isHidden: false,
  },

  // Glutes
  {
    id: toExerciseId('hip-thrust-barbell'),
    name: 'Hip Thrust',
    muscleGroup: 'glutes',
    source: 'catalog',
    equipment: 'barbell',
    isHidden: false,
  },
  {
    id: toExerciseId('glute-bridge-bodyweight'),
    name: 'Glute Bridge',
    muscleGroup: 'glutes',
    source: 'catalog',
    equipment: 'bodyweight',
    isHidden: false,
  },
  {
    id: toExerciseId('cable-kickback-cable'),
    name: 'Cable Kickback',
    muscleGroup: 'glutes',
    source: 'catalog',
    equipment: 'cable',
    isHidden: false,
  },
  {
    id: toExerciseId('hip-abduction-machine'),
    name: 'Hip Abduction',
    muscleGroup: 'glutes',
    source: 'catalog',
    equipment: 'machine',
    isHidden: false,
  },
  {
    id: toExerciseId('glute-ham-raise-other'),
    name: 'Glute Ham Raise',
    muscleGroup: 'glutes',
    source: 'catalog',
    equipment: 'other',
    isHidden: false,
  },
  {
    id: toExerciseId('trap-bar-deadlift-barbell'),
    name: 'Trap Bar Deadlift',
    muscleGroup: 'glutes',
    source: 'catalog',
    equipment: 'barbell',
    isHidden: false,
  },

  // Calves
  {
    id: toExerciseId('standing-calf-raise-machine'),
    name: 'Standing Calf Raise',
    muscleGroup: 'calves',
    source: 'catalog',
    equipment: 'machine',
    isHidden: false,
  },
  {
    id: toExerciseId('seated-calf-raise-machine'),
    name: 'Seated Calf Raise',
    muscleGroup: 'calves',
    source: 'catalog',
    equipment: 'machine',
    isHidden: false,
  },
  {
    id: toExerciseId('calf-press-on-leg-press-machine'),
    name: 'Calf Press on Leg Press',
    muscleGroup: 'calves',
    source: 'catalog',
    equipment: 'machine',
    isHidden: false,
  },
  {
    id: toExerciseId('calf-raise-bodyweight'),
    name: 'Calf Raise',
    muscleGroup: 'calves',
    source: 'catalog',
    equipment: 'bodyweight',
    isHidden: false,
  },
  {
    id: toExerciseId('calf-raise-single-leg-bodyweight'),
    name: 'Calf Raise Single Leg',
    muscleGroup: 'calves',
    source: 'catalog',
    equipment: 'bodyweight',
    isHidden: false,
  },

  // Abs
  {
    id: toExerciseId('sit-up-bodyweight'),
    name: 'Sit Up',
    muscleGroup: 'abs',
    source: 'catalog',
    equipment: 'bodyweight',
    isHidden: false,
  },
  {
    id: toExerciseId('hanging-leg-raise-bodyweight'),
    name: 'Hanging Leg Raise',
    muscleGroup: 'abs',
    source: 'catalog',
    equipment: 'bodyweight',
    isHidden: false,
  },
  {
    id: toExerciseId('cable-crunch-cable'),
    name: 'Cable Crunch',
    muscleGroup: 'abs',
    source: 'catalog',
    equipment: 'cable',
    isHidden: false,
  },
  {
    id: toExerciseId('machine-crunch-machine'),
    name: 'Machine Crunch',
    muscleGroup: 'abs',
    source: 'catalog',
    equipment: 'machine',
    isHidden: false,
  },
  {
    id: toExerciseId('ab-wheel-rollout-other'),
    name: 'Ab Wheel Rollout',
    muscleGroup: 'abs',
    source: 'catalog',
    equipment: 'other',
    isHidden: false,
  },

  // Traps
  {
    id: toExerciseId('shrug-barbell'),
    name: 'Shrug',
    muscleGroup: 'traps',
    source: 'catalog',
    equipment: 'barbell',
    isHidden: false,
  },
  {
    id: toExerciseId('shrug-dumbbell'),
    name: 'Shrug',
    muscleGroup: 'traps',
    source: 'catalog',
    equipment: 'dumbbell',
    isHidden: false,
  },
  {
    id: toExerciseId('shrug-cable'),
    name: 'Shrug',
    muscleGroup: 'traps',
    source: 'catalog',
    equipment: 'cable',
    isHidden: false,
  },
] as const;
