import { runAsync } from './async';
import { deepClone } from './clone';
import { ConflictError, NotFoundError } from './errors';

// The generic "table" primitive the in-memory engine is built from — see 07 · Persistence
// Layer Contract and task 022 ("in-memory storage core"). A collection knows nothing about
// any specific domain entity or repository interface: it just holds records keyed by id,
// the same shape a repository will need regardless of what it stores (muscle groups,
// exercises, sessions, set logs, ...).
//
// Every record must already carry its id — see rule 3: "Identifiers are generated by the
// domain, not the store." A collection never invents one.
export type Identifiable = { id: string };

export class InMemoryCollection<T extends Identifiable> {
  private rows = new Map<string, T>();

  /**
   * @param entityName Human-readable name used in error messages (e.g. "Exercise").
   */
  constructor(private readonly entityName: string) {}

  /** Inserts a new record. Rejects with `ConflictError` if the id is already taken. */
  insert(row: T): Promise<T> {
    return runAsync(() => {
      if (this.rows.has(row.id)) {
        throw new ConflictError(`${this.entityName} with id "${row.id}" already exists.`);
      }
      // Clone on the way in too: the caller's object must not become a live handle onto
      // stored state that later mutations of the caller's copy would leak into the store.
      const stored = deepClone(row);
      this.rows.set(stored.id, stored);
      return deepClone(stored);
    });
  }

  /** Reads one record by id. Rejects with `NotFoundError` if it does not exist. */
  getById(id: string): Promise<T> {
    return runAsync(() => {
      const row = this.rows.get(id);
      if (!row) {
        throw new NotFoundError(`${this.entityName} with id "${id}" was not found.`);
      }
      return deepClone(row);
    });
  }

  /** Reads one record by id, or `undefined` if it does not exist. */
  findById(id: string): Promise<T | undefined> {
    return runAsync(() => {
      const row = this.rows.get(id);
      return row ? deepClone(row) : undefined;
    });
  }

  /** Reads every record whose id is in `ids`, preserving their order. Missing ids are skipped. */
  listByIds(ids: string[]): Promise<T[]> {
    return runAsync(() => {
      const found: T[] = [];
      for (const id of ids) {
        const row = this.rows.get(id);
        if (row) {
          found.push(deepClone(row));
        }
      }
      return found;
    });
  }

  /** Reads every record in the collection. */
  list(): Promise<T[]> {
    return runAsync(() => Array.from(this.rows.values(), (row) => deepClone(row)));
  }

  /** Reads every record matching `predicate`. */
  find(predicate: (row: T) => boolean): Promise<T[]> {
    return runAsync(() =>
      Array.from(this.rows.values())
        .filter(predicate)
        .map((row) => deepClone(row)),
    );
  }

  /**
   * Replaces an existing record with the result of `updater`, called with a private copy
   * of the current record. Rejects with `NotFoundError` if `id` does not exist, or with
   * `ConflictError` if `updater` changes the id.
   */
  update(id: string, updater: (current: T) => T): Promise<T> {
    return runAsync(() => {
      const current = this.rows.get(id);
      if (!current) {
        throw new NotFoundError(`${this.entityName} with id "${id}" was not found.`);
      }
      const next = updater(deepClone(current));
      if (next.id !== id) {
        throw new ConflictError(`Cannot change the id of ${this.entityName} "${id}" on update.`);
      }
      const stored = deepClone(next);
      this.rows.set(id, stored);
      return deepClone(stored);
    });
  }

  /** Deletes a record by id. Rejects with `NotFoundError` if it does not exist. */
  delete(id: string): Promise<void> {
    return runAsync(() => {
      if (!this.rows.delete(id)) {
        throw new NotFoundError(`${this.entityName} with id "${id}" was not found.`);
      }
    });
  }

  /**
   * Point-in-time copy of every row, for the store's transaction snapshot/rollback.
   * Not part of the collection's public read/write contract — only `InMemoryStore` calls
   * this and {@link restoreRows}.
   * @internal
   */
  snapshotRows(): T[] {
    return Array.from(this.rows.values(), (row) => deepClone(row));
  }

  /**
   * Replaces the collection's contents with `rows`, e.g. to undo a failed transaction.
   * @internal
   */
  restoreRows(rows: T[]): void {
    this.rows = new Map(rows.map((row) => [row.id, deepClone(row)]));
  }
}
